MvcCoreAWSS3/Models/ErrorViewModel.cs
namespace MvcCoreAWSS3.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcCoreAWSS3/Controllers/AWSFilesController.cs
using Microsoft.AspNetCore.Mvc;
using MvcCoreAWSS3.Services;

namespace MvcCoreAWSS3.Controllers
{
    public class AWSFilesController : Controller
    {
        private ServiceStorageS3 service;

        private string BucketUrl;
        public AWSFilesController
            (ServiceStorageS3 service, IConfiguration configuration)
        {
            this.BucketUrl = configuration.GetValue<string>("AWS:BucketUrl");
            this.service = service;
        }

        public async Task<IActionResult> Index()
        {   
            List<string> filesS3 = await this.service.GetVersionsFileAsync();
            ViewData["BUCKETURL"] = this.BucketUrl;
            return View(filesS3);
        }


        public IActionResult UploadFile()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> UploadFile(IFormFile file)
        {
            using(Stream stream = file.OpenReadStream())
            {
                await this.service.UploadFileAsync(file.FileName, stream);

            }
            return RedirectToAction("Index");
        }

        //SI DESEAMOS VISUALIZAR EL FICHERO POR SI FUERA PRIVADO
        public async Task<IActionResult> FileAWS(string fileName)
        {
            Stream stream = await this.service.GetFileAsync(fileName);
            return File(stream, "image/png");
        }


        public async Task<IActionResult> DeleteFile(string fileName)
        {
            await this.service.DeleteFileAsync(fileName);
            return RedirectToAction("Index");
        }


    }
}

MvcCoreAWSS3/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MvcCoreAWSS3.Models;
using System.Diagnostics;

namespace MvcCoreAWSS3.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcCoreAWSS3/Views/AWSFiles/Index.cshtml
@model List<string>

<h1 style="color:blue">
    AWS Service Storage S3
</h1>

<a asp-controller="AWSFiles" asp-action="UploadFile"
class="btn btn-info">
    Upload File
</a>

<hr/>


<ul class="list-group">
    @foreach(string fileName in Model)
    {
        <li class="list-group-item">
            @fileName
            <img src="@ViewData["BUCKETURL"]@fileName"
            style="width:150px; height: 150px" />
            <a asp-controller="AWSFiles" asp-action="FileAWS"
            class="btn btn-warning"
            asp-route-filename="@fileName">Ver fichero (Private)</a>
            <a asp-controller="AWSFiles" asp-action="DeleteFile"
               class="btn btn-dark"
           asp-route-filename="@fileName">Delete File</a>
        </li>
    }

</ul>

MvcCoreAWSS3/Views/AWSFiles/UploadFile.cshtml
<h1 style="color:red">
    Upload File AWS S3
</h1>

<form method="post" enctype="multipart/form-data">
    <label>Selecciona un fichero</label>    
    <input type="file" name="file" class="form-control" />
    <button class="btn btn-info">
        Upload file
    </button>
</form>

MvcCoreAWSS3/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MvcCoreAWSS3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcCoreAWSS3</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcCoreAWSS3.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcCoreAWSS3</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" 
                            asp-area=""
                            asp-controller="AWSFiles" 
                            asp-action="Index">AWS</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MvcCoreAWSS3 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>